config/routes.rb
TestViye::Application.routes.draw do
  resources :posts

  devise_for :users
  get "home/index"

  root "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
  def index
  	@post = Post.all.take(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div id="MY-SLIDE-BAR">
			<div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
		        <ol class="carousel-indicators">
		          <li data-target="#carousel-example-captions" data-slide-to="0" class=""></li>
		          <li data-target="#carousel-example-captions" data-slide-to="1" class=""></li>
		          <li data-target="#carousel-example-captions" data-slide-to="2" class="active"></li>
		        </ol>
		        <div class="carousel-inner">
		          <div class="item slide-content">
		          	<div class="content-left"><a class="img-wrapper" href="#"><%= image_tag("l1.jpg")%></a></div>
		          	<div class="content-right">
		          	<a class="my-title" href="#"><h3><%= @post[0].title %></h3></a>
		          	<div class="my-vote">
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-2"></span>
		          		<span class="vote-span">Điểm đánh giá: <span class="vote-mark">(4.3/5)</span></span>
		          	</div>
		          	<p><%= truncate(@post[0].content, length: 600, separator: ' ') %></p>
		            
		            <%=link_to '<button class="default-button" type="button" >Xem thêm</button>'.html_safe, @post[0] %>
		          	</div>
		          </div>
		          <div class="item slide-content">
		            <div class="content-left"><a class="img-wrapper" href="#"><%= image_tag("l2.jpg")%></a></div>
		          	<div class="content-right">
		          	<a class="my-title" href="#"><h3><%= @post[1].title %></h3></a>
		          	<div class="my-vote">
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-2"></span>
		          		<span class="vote-span">Điểm đánh giá: <span class="vote-mark">(4.3/5)</span></span>
		          	</div>
		          	<p><%= truncate(@post[1].content, length: 600, separator: ' ') %></p>
		            
		            <%=link_to '<button class="default-button" type="button" >Xem thêm</button>'.html_safe, @post[1] %>
		          	</div>
		          </div>
		          <div class="item slide-content active">
		            <div class="content-left"><a class="img-wrapper" href="#"><%= image_tag("l4.jpg")%></a></div>
		          	<div class="content-right">
		          	<a class="my-title" href="#"><h3><%= @post[2].title %></h3></a>
		          	<div class="my-vote">
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-1"></span>
		          		<span class="glyphicon glyphicon-star star-2"></span>
		          		<span class="vote-span">Điểm đánh giá: <span class="vote-mark">(4.3/5)</span></span>
		          	</div>
		          	<p><%= truncate(@post[2].content, length: 600, separator: ' ') %></p>
		            
		            <%=link_to '<button class="default-button" type="button" >Xem thêm</button>'.html_safe, @post[2] %>
		          	</div>
		          </div>
		        </div>
		        <a class="left carousel-control" href="#carousel-example-captions" data-slide="prev">
		          <span class="glyphicon glyphicon-chevron-left"></span>
		        </a>
		        <a class="right carousel-control" href="#carousel-example-captions" data-slide="next">
		          <span class="glyphicon glyphicon-chevron-right"></span>
		        </a>
		    </div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TestViye</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div id="MY-HEADER">
		<div id="MY-LOGO">
			<a href=<%= home_index_path %> ><%= image_tag("viye_3.png")%></a>
		</div>
		<div id="MY-SEARCH">
			<input type="text" placeholder="hãy gõ từ khóa vào đây!">
			<button type="button" class="search-button">Tìm kiếm</button>
		</div>

		<div id="MY-LOGIN">
			<div id="user_nav">
				<% if user_signed_in? %>
				Signed in as <%= current_user.email %>. Not you?
				<%= link_to "Sign out", destroy_user_session_path %>
				<% else %>
				<!-- day la phan dang ki -->				
				<div class="popover-markup">
					<button type="button" class="pop-btn search-button">Đăng ký</button>
					<div id="popover-signup-content" class="popover-content hide">
						<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :class=>"form-horizontal") do |f| %>
						<%= devise_error_messages! %>
						<div class="control-group">
							<label class="control-label" for="inputEmail">Email</label>
							<div class="controls">
								<%= f.email_field :email, :autofocus => true, :class=>"my-text-form", :placeholder=>"Example@gmail.com" %>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="inputPassword">Password</label>
							<div class="controls">
								<%= f.password_field :password , :class=>"my-text-form", :placeholder=>"Mật khẩu"%>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="inputPassword">Password</label>
							<div class="controls">
								<%= f.password_field :password_confirmation , :class=>"my-text-form", :placeholder=>"Mật khẩu"%>
							</div>
						</div>
						<div class="control-group">
							<div><%= f.submit "Sign up" , :class=>"login-button" %></div>
						</div>
						<% end %>		
					</div>
				</div>
				<!-- het phan dang ki -->						


				<!-- day la phan dang nhap -->
				<div class="popover-markup">
					<button type="button" class="pop-btn search-button">Đăng nhập</button>
					<div id="popover-login-content" class="popover-content hide">

						<%= form_for("user", :url => user_session_path, :class=>"form-horizontal") do |f| %>
						<div class="control-group">
							<label class="control-label" for="inputEmail">Email</label>
							<div class="controls">
								<%= f.text_field :email , :class=>"my-text-form", :placeholder=>"Email"%>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="inputPassword">Password</label>
							<div class="controls">
								<%= f.password_field :password , :class=>"my-text-form", :placeholder=>"Mật khẩu" %>
							</div>
						</div>
						<br>
						<%= f.check_box :remember_me %>
						<%= f.label :remember_me %>
						<%= f.submit 'Sign in', :class=>"login-button" %>
						<% end %>
						<% end %>
					</div>
				</div>
			</div>
			<!-- het phan dang nhap -->
		</div>
	</div>

<!-- 	<% if notice %>
	<p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-error"><%= alert %></p>
	<% end %> -->





	<%= yield %>

	<!-- day la javascript -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>